### ISSUE TITLE
Could not start SASL: Error in sasl_client_start (-4) SASL(-4)

### ISSUE THREAD

**Issue by kotharisonal** [BradRuderman/pyhs2#41]
I have CentOs 6.6 running Python 2.6. I installed python 2.7 in a separate localtion /usr/local/bin for being able to use the pyh2 hive client. I installed all the additional packages needed. Eg. all the SASL packages are available: 

[tap@localhost test]$ rpm -qa | grep sasl
cyrus-sasl-gssapi-2.1.23-15.el6_6.1.x86_64
cyrus-sasl-lib-2.1.23-15.el6_6.1.x86_64
cyrus-sasl-md5-2.1.23-15.el6_6.1.x86_64
cyrus-sasl-2.1.23-15.el6_6.1.x86_64
cyrus-sasl-plain-2.1.23-15.el6_6.1.x86_64
cyrus-sasl-devel-2.1.23-15.el6_6.1.x86_64

But I still see the following error:
/usr/local/lib/python2.7/site-packages/setuptools-12.3-py2.7.egg/pkg_resources/__init__.py:1224: UserWarning: /home/tap/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Traceback (most recent call last):
  File "testPktFlow2.py", line 7, in <module>
    database='default') as conn:
  File "build/bdist.linux-x86_64/egg/pyhs2/__init__.py", line 7, in connect
  File "build/bdist.linux-x86_64/egg/pyhs2/connections.py", line 45, in __init__
  File "build/bdist.linux-x86_64/egg/pyhs2/cloudera/thrift_sasl.py", line 66, in open
thrift.transport.TTransport.TTransportException: Could not start SASL: Error in sasl_client_start (-4) SASL(-4): no mechanism available: No worthy mechs found

**Comment by zklopman** [comment]
Hello,

this error message:

/usr/local/lib/python2.7/site-packages/setuptools-12.3-py2.
7.egg/pkg_resources/*init*.py:1224: UserWarning: /home/tap/.python-eggs is
writable by group/others and vulnerable to attack when used with
get_resource_filename. Consider a more secure location (set with
.set_extraction_path or the PYTHON_EGG_CACHE environment variable).

means that the permissions on the file .python-eggs are too open. Try
running this:

chmod 007  /home/tap/.python-eggs

which will prevent others from accessing the nest and see if that solves
your problem.

bye,

Zachi

**Comment by kotharisonal** [comment]
Thanks but I am stalled by the Error in SASL client. How do I resolve that.

**Comment by zklopman** [comment]
Hi,

If you have fixed the permissions issue and it is still a problem, you
might check the resolution of a similar problem at
https://github.com/BradRuderman/pyhs2/issues/19 .

bye,

Zachi
