### ISSUE TITLE
ImportError: No module named _saslwrapper, 

### ISSUE THREAD

**Issue by atuldata** [BradRuderman/pyhs2#52]
Traceback (most recent call last):
  File "atul_api.py", line 14, in <module>
    database='rashmi') as conn:
  File "/usr/lib64/python2.6/site-packages/pyhs2/__init__.py", line 6, in connect
    from .connections import Connection
  File "/usr/lib64/python2.6/site-packages/pyhs2/connections.py", line 6, in <module>
    import sasl
  File "/usr/lib64/python2.6/site-packages/sasl/__init__.py", line 1, in <module>
    from sasl.saslwrapper import *
  File "/usr/lib64/python2.6/site-packages/sasl/saslwrapper.py", line 6, in <module>
    import _saslwrapper
ImportError: No module named _saslwrapper

**Comment by kkennedy314** [comment]
The SASL wrapper for Python needs to be installed. On CentOS/RHEL, you can do the following:
  sudo yum install gcc-c++ python-devel.x86_64 cyrus-sasl-devel.x86_64

Additionally, you can also do it from source:
  curl -O -L ftp://ftp.cyrusimap.org/cyrus-sasl/cyrus-sasl-2.1.26.tar.gz
  tar xzf cyrus-sasl-2.1.2.26.tar.gz
  cd cyrus-sasl-2.1.26.tar.gz
  ./configure && make install

**Comment by adtrombley** [comment]
This didn't work, error 

atrombley@RPTTEST102 ~/Desktop/rfc (master)
$ tar xzf C:\Users\atrombley\Desktop\rfc\cyrus-sasl-2.1.2.26.tar.gz
tar (child): Cannot execute remote shell: No such file or directory
tar (child): C:UsersatrombleyDesktoprfccyrus-sasl-2.1.2.26.tar.gz: Cannot open:
 I/O error
tar (child): Error is not recoverable: exiting now

gzip: stdin: unexpected end of file
tar: Child returned status 2
tar: Exiting with failure status due to previous errors
