### ISSUE TITLE
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes

### ISSUE THREAD

**Issue by v23Codes** [BradRuderman/pyhs2#72]
I'm trying to connect to hive using python. I tried using both pyhive and pyhs2 but it gives the following error.

Traceback (most recent call last):
  File "hello.py", line 8, in <module>
    database='hello') as conn:
  File "/usr/local/lib/python2.7/dist-packages/pyhs2/__init__.py", line 7, in connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyhs2/connections.py", line 47, in __init__
    res = self.client.OpenSession(TOpenSessionReq(username=user, password=password, configuration=configuration))
  File "/usr/local/lib/python2.7/dist-packages/pyhs2/TCLIService/TCLIService.py", line 154, in OpenSession
    return self.recv_OpenSession()
  File "/usr/local/lib/python2.7/dist-packages/pyhs2/TCLIService/TCLIService.py", line 165, in recv_OpenSession
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
  File "build/bdist.linux-x86_64/egg/thrift/protocol/TBinaryProtocol.py", line 148, in readMessageBegin
  File "build/bdist.linux-x86_64/egg/thrift/transport/TTransport.py", line 60, in readAll
  File "build/bdist.linux-x86_64/egg/thrift/transport/TTransport.py", line 161, in read
  File "build/bdist.linux-x86_64/egg/thrift/transport/TSocket.py", line 132, in read
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes

Nothing mentioned in forums or internet was able to help me bypass this issue. Is there a workaround for this ?

**Comment by anderl80** [comment]
Any progress with this one?
